name: C++ Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libsfml-dev xvfb

      - name: Set up CMake
        run: sudo apt-get install -y cmake

      - name: Create build directory
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run the application with Xvfb
        run: xvfb-run ./build/xonix

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install CMake and SFML
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          choco install sfml

      - name: Set environment variables for SFML
        run: |
          echo "SFML_DIR=C:\Program Files (x86)\SFML" >> $GITHUB_ENV
          echo "PATH=$env:PATH;C:\Program Files (x86)\SFML\bin" >> $GITHUB_ENV
  
      - name: Create build directory
        run: |
          mkdir build
          cd build
          cmake -DSFML_DIR="C:\Program Files (x86)\SFML" ..
          cmake --build . --config Release

      - name: Run the application
        run: |
          cd build/Release
          .\xonix.exe
